version: '3.8'

services:
  test_web:
    container_name: test_web
    env_file:
      - .env
    build:
      context: ./src
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL_TEST}
    expose:
      - 5432
    depends_on:
      test_db:
        condition: service_healthy

  test_db:
    container_name: test_db
    env_file:
      - .env
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
