version: '3.8'

services:
  web:
    env_file:
      - .env
    build:
      context: ./src
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    expose:
      - 5432
    depends_on:
      db:
        condition: service_healthy

  db:
    env_file:
      - .env
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
